name: Test and Debug Script

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: '1.84.0'

      - name: Install dependencies
        run: sudo apt-get install -y libssl-dev pkg-config

      - name: Build the project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run the script
        run: cargo run --verbose